# This is the network config written by 'subiquity'
network:
  ethernets:
    ens18:
      addresses:
      - 172.20.15.50/24
      gateway4: 172.20.15.1
      nameservers:
        addresses:
        - 8.8.8.8
        - 8.8.4.4
        search: []
  version: 2